'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Sprout,Plus,Package,Droplets,Trees,ClipboardList,Pencil,Trash2,Download,RefreshCw,WifiOff,NotebookPen,CloudCheck,LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Empty,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Toaster,toast} from 'sonner';
import {varieties,activeTreatments,today,weight,saleValue,harvestMatches,plotVarieties,plotFruit,seasonStats,treesFor,applyMutation,recordSchema,type OrchardRecord,type Plot,type Kind,type Mutation,type Stock} from '@/lib/orchard';
import {Warehouse,InventoryForm,MaterialsField} from './orchard-inventory';
import {PlanList,PlanForm,GrowthStageField} from './orchard-plans';
import {stageLabel} from '@/lib/growth-stages';
import OrchardStatistics from './orchard-statistics';
import {readDevice,writeDevice,type DeviceState} from '@/lib/device-cache';

const fmt=(n:number)=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:2}).format(n);
const day=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('pl-PL',{day:'numeric',month:'short'});
const titles:Record<Kind,string>={plot:'Kwatera',harvest:'Zbiór',treatment:'Zabieg',trees:'Zmiana liczby drzew',observation:'Obserwacja',stock:'Środek w magazynie',purchase:'Zakup środka',plan:'Przypomnienie'};
function Choice({label,value,onChange,options}:{label:string,value:string,onChange:(v:string)=>void,options:{value:string,label:string}[]}){return <div><span className="field-label">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
function EmptyState({title,description,action,onClick}:{title:string,description:string,action?:string,onClick?:()=>void}){return <Empty className="empty"><Package/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription>{action&&<button className="button" onClick={onClick}><Plus size={18}/>{action}</button>}</Empty>}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export default function Orchard(){
 const [device,setDevice]=useState<DeviceState|null>(null),deviceRef=useRef<DeviceState|null>(null);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState(false),[offline,setOffline]=useState(false),[syncing,setSyncing]=useState(false);
 const syncLock=useRef(false),ownsDevice=useRef(false);
 const [tab,setTab]=useState('summary'),[year,setYear]=useState(today().slice(0,4)),[filter,setFilter]=useState('all');
 const [fruit,setFruit]=useState('sour'),[workFilter,setWorkFilter]=useState('Oprysk');
 const [modal,setModal]=useState<{kind:Kind,record?:OrchardRecord,defaultVariety?:string,defaultTreatment?:string}|null>(null),[remove,setRemove]=useState<OrchardRecord|null>(null),[install,setInstall]=useState<any>(null);
 const [formError,setFormError]=useState(''),[busy,setBusy]=useState(false);
 async function commit(v:DeviceState){await writeDevice(v);deviceRef.current=v;setDevice(v)}
 async function sync(){
  if(!ownsDevice.current||syncLock.current)return;syncLock.current=true;setSyncing(true);
  try{
   const r=await fetch('/api/farm',{cache:'no-store'});const data=await r.json() as {farm:DeviceState['farm'],userId:string,error?:string};
   if(r.status===401){setAuth(true);setDevice(null);throw new Error(data.error)}
   if(!r.ok)throw new Error(data.error||'Nie udało się wczytać danych.');
   setAuth(false);setOffline(false);
   const old=deviceRef.current;let current:DeviceState={farm:data.farm,userId:data.userId,pending:old&&old.userId===data.userId?old.pending:[]};
   await commit(current);
   while(current.pending.length){
    const m=current.pending[0];const response=await fetch('/api/farm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(m)});const result=await response.json() as {farm:DeviceState['farm'],error?:string};
    if(!response.ok){if(response.status===401)setAuth(true);throw new Error(result.error||'Zapis nie powiódł się.')}
    current={...current,farm:result.farm,pending:current.pending.slice(1)};await commit(current);
   }
   setError('');
  }catch(e){setOffline(!navigator.onLine);setError((e as Error).message||'Brak połączenia. Spróbuj ponownie.');}
  finally{syncLock.current=false;setSyncing(false);setLoading(false)}
 }
 useEffect(()=>{let active=true;let release:(()=>void)|undefined;
  const boot=async()=>{ownsDevice.current=true;try{const v=await readDevice();if(active){deviceRef.current=v;setDevice(v);await sync()}}catch{setError('Pamięć telefonu jest niedostępna. Zezwól przeglądarce na zapis danych.');setLoading(false)}};
  if(navigator.locks){void navigator.locks.request('moj-sad-device-editor',{ifAvailable:true},async lock=>{if(!active)return;if(!lock){setError('Mój Sad jest już otwarty w innej karcie. Zamknij ją i odśwież tę stronę, aby bezpiecznie edytować dane.');setLoading(false);return}const lifetime=new Promise<void>(resolve=>{release=resolve});await boot();await lifetime}).catch(()=>{setError('Nie udało się otworzyć rejestru na tym urządzeniu. Odśwież stronę.');setLoading(false)})}else{void boot()}
  const online=()=>{setOffline(false);void sync()};const off=()=>setOffline(true);const installHandler=(e:Event)=>{e.preventDefault();setInstall(e)};window.addEventListener('online',online);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',installHandler);
  if('serviceWorker' in navigator&&process.env.NODE_ENV==='production')navigator.serviceWorker.register('/sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>{const urls=performance.getEntriesByType('resource').map(e=>e.name);reg.active?.postMessage({type:'warm',urls})}).catch(()=>{});
  return()=>{active=false;ownsDevice.current=false;release?.();window.removeEventListener('online',online);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',installHandler)};
 },[]);
 let records=device?.farm.records??[];
 for(const m of device?.pending??[]){try{records=applyMutation({records,appliedIds:[]},m).records}catch{/* Conflicting pending data remains visible in the queue. */}}
 const plots=records.filter((r):r is Plot=>r.kind==='plot');
 const stocks=records.filter((r):r is Stock=>r.kind==='stock');
 const pendingIds=new Set((device?.pending??[]).map(m=>m.action==='upsert'?m.record.id:m.id));
 const seasonal=records.filter(r=>r.date.slice(0,4)===year);
 const harvests=seasonal.filter((r):r is Extract<OrchardRecord,{kind:'harvest'}>=>r.kind==='harvest');
 const works=seasonal.filter(r=>r.kind==='treatment'||r.kind==='observation');
 const visibleHarvests=harvests.filter(r=>harvestMatches(r,fruit,filter));
 const visibleWorks=works.filter(r=>workFilter==='history'?r.kind==='observation'||(r.kind==='treatment'&&!activeTreatments.includes(r.treatment as any)):r.kind==='treatment'&&r.treatment===workFilter);
 const priced=visibleHarvests.filter(r=>r.pricePerKg!=null);
 const changes=seasonal.filter(r=>r.kind==='trees');
 const season=seasonStats(records,year);
 const currentTrees=plots.reduce((s,p)=>s+treesFor(p,records),0);
 const costs=works.reduce((s,r)=>s+(r.kind==='treatment'?r.cost:0),0);
 const water=works.reduce((s,r)=>s+(r.kind==='treatment'&&r.treatment==='Podlewanie'?(r.unit==='m³'?r.amount:r.unit==='l'?r.amount/1000:0):0),0);
 const years=Array.from(new Set([today().slice(0,4),...records.map(r=>r.date.slice(0,4))])).filter(y=>y!=='2025').sort().reverse();
 const varietyStats=varieties.map(v=>({name:v,kg:harvests.filter(r=>r.variety===v).reduce((s,r)=>s+weight(r),0)}));
 const sorted=(list:OrchardRecord[])=>[...list].sort((a,b)=>b.date.localeCompare(a.date));
 const plotName=(id:string|null)=>plots.find(p=>p.id===id)?.name||'Cały sad / bez kwatery';
 function start(kind:Kind,record?:OrchardRecord){setFormError('');setModal({kind,record,defaultVariety:tab==='harvest'&&fruit==='sweet'?(filter==='all'?'Wanda':filter):'Łutówka',defaultTreatment:tab==='work'&&workFilter!=='history'?workFilter:'Oprysk'})}
 async function save(record:OrchardRecord){
  if(!deviceRef.current)throw new Error('Najpierw wczytaj gospodarstwo z połączeniem internetowym.');
  if(syncLock.current)throw new Error('Poczekaj na zakończenie synchronizacji.');
  const parsed=recordSchema.safeParse(record);if(!parsed.success)throw new Error('Sprawdź wymagane pola i wartości liczbowe.');
  const m:Mutation={action:'upsert',requestId:crypto.randomUUID(),record:parsed.data,expectedVersion:record.version};
  let farm=deviceRef.current.farm;for(const pending of deviceRef.current.pending)farm=applyMutation(farm,pending);applyMutation(farm,m);
  await commit({...deviceRef.current,pending:[...deviceRef.current.pending,m]});setModal(null);toast.success('Wpis dodany do kolejki zapisu.');await sync();
 }
 async function deleteRecord(){
  if(!remove||!deviceRef.current)return;setBusy(true);
  try{
   if(syncLock.current)throw new Error('Poczekaj na zakończenie synchronizacji.');
   const d=deviceRef.current;
   if(pendingIds.has(remove.id))throw new Error('Najpierw zsynchronizuj wpis lub odrzuć go z kolejki.');
   const m:Mutation={action:'delete',requestId:crypto.randomUUID(),id:remove.id,expectedVersion:remove.version};
   applyMutation(d.farm,m);await commit({...d,pending:[...d.pending,m]});setRemove(null);await sync();
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 function exportCSV(){
  const rows=[['Data','Rodzaj','Kwatera','Odmiana','Skrzynki 5 kg','Skrzynki 10 kg','Masa kg','Sposób podania masy','Cena zł/kg','Wartość sprzedaży zł','Zabieg / opis','Ilość','Jednostka','Koszt PLN','Zmiana drzew','Uwagi','Gatunek zabiegu','Faza rozwoju','Zużycie z magazynu'],...sorted(seasonal.filter(r=>r.kind!=='plot')).map(r=>[r.date,titles[r.kind],'plotId'in r?plotName(r.plotId):'', 'variety'in r?r.variety:'',r.kind==='harvest'?r.boxes5:'',r.kind==='harvest'?r.boxes10:'',r.kind==='harvest'?weight(r):'',r.kind==='harvest'?(r.weightKg!=null?'Kilogramy':'Przeliczenie skrzynek'):'',r.kind==='harvest'?(r.pricePerKg??''):'',r.kind==='harvest'&&r.pricePerKg!=null?saleValue(r):'',r.kind==='treatment'?(r.treatment+' '+r.product):r.kind==='purchase'?(stocks.find(s=>s.id===r.stockId)?.name||''):'name'in r?r.name:'',r.kind==='treatment'||r.kind==='purchase'?r.amount:r.kind==='stock'?r.initialAmount:'',r.kind==='treatment'||r.kind==='purchase'||r.kind==='stock'?r.unit:'',r.kind==='treatment'?r.cost:'',r.kind==='trees'?r.treeChange:'',r.note,r.kind==='treatment'?(r.fruit==='sour'?'Wiśnie':r.fruit==='sweet'?'Czereśnie':''):'',r.kind==='treatment'||r.kind==='plan'?stageLabel(r.stage):'',r.kind==='treatment'?(r.materials??[]).map(m=>(stocks.find(s=>s.id===m.stockId)?.name||m.stockId)+' '+m.amount+' '+m.unit).join(' | '):''])];
  const safe=(s:unknown)=>{let v=String(s);if(/^[=+@\-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'};
  download(`moj-sad-${year}.csv`,'\uFEFF'+rows.map(row=>row.map(safe).join(';')).join('\r\n'),'text/csv;charset=utf-8');
 }
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tool={name:'read_orchard_summary',title:'Podsumowanie sadu',description:'Odczytuje podsumowanie aktualnie wybranego sezonu oraz zapisane odmiany; nie zmienia danych.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Oczekiwano pustego obiektu.');return{season:year,wiśnie:season.sour,czereśnie:season.sweet,salesValue:season.sales,recordedCosts:season.costs,recordedResult:season.result,currentTrees,varieties:varietyStats,pending:device?.pending.length??0}}};
  Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
 },[year,currentTrees,device]);
 function RecordList({list}:{list:OrchardRecord[]}){return <>{sorted(list).map(r=><div className="record" key={r.id}><div><strong>{r.kind==='harvest'?r.variety:r.kind==='treatment'?r.treatment:r.kind==='observation'?r.name:r.kind==='trees'?(r.treeChange<0?'Ubytek drzew':'Dosadzenie'):r.kind==='purchase'?'Zakup: '+(stocks.find(s=>s.id===r.stockId)?.name||'środek'):r.name}</strong>{pendingIds.has(r.id)&&<span className="badge">Oczekuje</span>}<p>{day(r.date)} · {'plotId'in r?plotName(r.plotId):''}</p>{r.kind==='harvest'&&<><p><b>{fmt(weight(r))} kg</b> · {r.weightKg!=null?'Wpisano w kilogramach':`${r.boxes5} × 5 kg + ${r.boxes10} × 10 kg`}</p><p>{r.pricePerKg!=null?`${fmt(r.pricePerKg)} zł/kg · sprzedaż ${fmt(saleValue(r))} zł`:'Cena sprzedaży niepodana'}</p></>}{r.kind==='treatment'&&<p>{r.product&&r.product+' · '}{fmt(r.amount)} {r.unit}{r.cost>0&&` · ${fmt(r.cost)} zł`}</p>}{r.kind==='purchase'&&<p>+{fmt(r.amount)} {r.unit}</p>}{r.kind==='stock'&&<p>Pierwszy zakup / stan początkowy: {fmt(r.initialAmount)} {r.unit}</p>}{r.kind==='treatment'&&<><p>{r.fruit?(r.fruit==='sour'?'Wiśnie':'Czereśnie')+' · ':''}{r.stage&&stageLabel(r.stage)}</p>{r.materials?.map(m=><p key={m.stockId}>{stocks.find(s=>s.id===m.stockId)?.name} · zużyto {fmt(m.amount)} {m.unit}</p>)}</>}{r.kind==='trees'&&<p>{r.treeChange>0?'+':''}{r.treeChange} drzew</p>}{r.note&&<p className="note-text">{r.note}</p>}</div><div className="record-actions"><button className="icon-btn" aria-label={`Edytuj ${titles[r.kind]} ${r.date}`} disabled={pendingIds.has(r.id)||syncing} onClick={()=>start(r.kind,r)}><Pencil/></button><button className="icon-btn" aria-label={`Usuń ${titles[r.kind]} ${r.date}`} disabled={pendingIds.has(r.id)||syncing} onClick={()=>setRemove(r)}><Trash2/></button></div></div>)}</>}
 return <div className="shell"><Toaster position="top-center" richColors/><header><div className="brand"><span className="brandmark"><Sprout/></span><strong>Mój Sad</strong></div><div className="header-right"><span className="sync">{syncing?<LoaderCircle size={16} className="spin"/>:offline?<WifiOff size={16}/>:<CloudCheck size={16}/>}<span>{syncing?'Zapisywanie…':offline?'Bez połączenia':device?.pending.length?`${device.pending.length} oczekuje`:'Dziennik gospodarstwa'}</span></span>{install&&<button className="link-btn" onClick={async()=>{await install.prompt();setInstall(null)}}>Zainstaluj</button>}</div></header><main>
 <div className="page-title"><div><p className="eyebrow">TWÓJ SAD W LICZBACH</p><h1>{tab==='summary'?'Przegląd sezonu':tab==='harvest'?'Zbiory':tab==='work'?'Dziennik zabiegów':tab==='statistics'?'Statystyki rok do roku':tab==='warehouse'?'Magazyn środków':'Kwatery i drzewa'}</h1></div><Choice label="Sezon" value={year} onChange={setYear} options={years.map(y=>({value:y,label:y}))}/></div>
 {loading&&<p className="notice">Wczytywanie gospodarstwa…</p>}
 {auth?<div className="notice error">Zaloguj się, aby otworzyć swój rejestr. <a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="link-btn">Zaloguj się</a></div>:error&&<div className="notice error" role="alert">{offline?'Brak internetu. Wpisy oczekują na przesłanie.':error} <button className="link-btn" onClick={()=>void sync()} disabled={syncing}>Spróbuj ponownie</button></div>}
 {!!device?.pending.length&&<details className="notice"><summary>Wpisy oczekujące na zapis: {device.pending.length}</summary><p>Do czasu synchronizacji są przechowywane na tym urządzeniu.</p>{device.pending.map(m=><div className="queue-item" key={m.requestId}><span>{m.action==='upsert'?`${titles[m.record.kind]} · ${m.record.date}`:'Usunięcie wpisu'}</span><button className="link-btn" disabled={syncing} onClick={async()=>{if(!deviceRef.current)return;await commit({...deviceRef.current,pending:deviceRef.current.pending.filter(p=>p.requestId!==m.requestId)});setError('')}}>Odrzuć oczekujący wpis</button></div>)}</details>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="nav"><TabsTrigger value="summary">Przegląd</TabsTrigger><TabsTrigger value="harvest">Zbiory</TabsTrigger><TabsTrigger value="statistics">Statystyki</TabsTrigger><TabsTrigger value="work">Zabiegi</TabsTrigger><TabsTrigger value="warehouse">Magazyn</TabsTrigger><TabsTrigger value="plots">Kwatery i drzewa</TabsTrigger></TabsList>
 <TabsContent value="summary"><div className="stats harvest-stats"><article className="stat accent"><Package/><p>Zebrane wiśnie</p><strong>{device?fmt(season.sour.kg):'—'} <small>kg</small></strong><span>Łutówka · {season.sour.entries} wpisów w sezonie</span></article><article className="stat"><Package/><p>Zebrane czereśnie</p><strong>{device?fmt(season.sweet.kg):'—'} <small>kg</small></strong><span>{fmt(season.sweet.boxes5)} skrzynek 5 kg · {fmt(season.sweet.boxes10)} skrzynek 10 kg</span></article><article className="stat"><ClipboardList/><p>Wynik po zapisanych kosztach</p><strong>{device?fmt(season.result):'—'} <small>zł</small></strong><span>Sprzedaż {fmt(season.sales)} zł · koszty {fmt(costs)} zł</span></article></div><p className="progress-note">Wynik finansowy obejmuje sprzedaż z podaną ceną i zapisane koszty zabiegów. {season.missingPrices>0&&('Wpisy bez ceny: '+season.missingPrices+'.')}</p><div className="toolbar season-details"><span className="muted">Drzewa obecnie: {plots.length?fmt(currentTrees):'—'} · kwatery: {plots.length} · ubytki w sezonie: {fmt(changes.reduce((s,r)=>s+(r.kind==='trees'&&r.treeChange<0?-r.treeChange:0),0))} · zabiegi: {works.filter(r=>r.kind==='treatment').length}</span><button className="link-btn" onClick={()=>setTab('statistics')}>Porównaj rok do roku</button></div>
 <PlanList compact records={records} plots={plots} disabled={!device||auth||syncing} pending={pendingIds} onAdd={start} onDelete={setRemove} onSave={save}/>
 <h2>Szybki wpis</h2><div className="actions"><button className="action" disabled={!device||auth} onClick={()=>start('harvest')}><Package/>Dodaj zbiór</button><button className="action" disabled={!device||auth} onClick={()=>start('treatment')}><Droplets/>Dodaj zabieg</button><button className="action" disabled={!device||auth} onClick={()=>start(plots.length?'trees':'plot')}><Trees/>{plots.length?'Zapisz ubytek':'Dodaj kwaterę'}</button><button className="action" disabled={!device||auth} onClick={()=>start('observation')}><NotebookPen/>Dodaj obserwację</button></div>
 <div className="two-cols"><section className="panel"><h2>Zbiory według odmiany</h2><Tabs value={fruit} onValueChange={v=>{setFruit(v);setFilter('all')}}><TabsList className="fruit-switch"><TabsTrigger value="sour">Wiśnie</TabsTrigger><TabsTrigger value="sweet">Czereśnie</TabsTrigger></TabsList></Tabs>{harvests.length>0?<div className="bars">{varietyStats.filter(v=>fruit==='sour'?v.name==='Łutówka':v.name!=='Łutówka').map(v=><div key={v.name}><div className="bar-label"><strong>{v.name}</strong><span>{fmt(v.kg)} kg</span></div><div className="bar-track"><div className="bar-fill" style={{width:`${v.kg/Math.max(...varietyStats.filter(x=>fruit==='sour'?x.name==='Łutówka':x.name!=='Łutówka').map(x=>x.kg),1)*100}%`}}/></div></div>)}</div>:<EmptyState title="Pierwszy zbiór przed Tobą" description="Wpisz kilogramy wiśni lub liczbę skrzynek. Tutaj zobaczysz wyniki każdej odmiany." action={device&&!auth?'Dodaj zbiór':undefined} onClick={()=>start('harvest')}/>}<p className="progress-note">Masa danego gatunku obejmuje wpisane kilogramy i przeliczone skrzynki.</p></section><section className="panel"><div className="toolbar"><h2>Ostatnie wpisy</h2><button className="icon-btn" aria-label="Odśwież dane" disabled={syncing} onClick={()=>void sync()}><RefreshCw/></button></div>{seasonal.filter(r=>r.kind!=='plot').length?<RecordList list={sorted(seasonal.filter(r=>r.kind!=='plot')).slice(0,4)}/>:<EmptyState title="Twój dziennik jest gotowy" description="Zapisuj zbiory, prace i obserwacje. Historia sezonu pojawi się tutaj."/>}</section></div>
 <section className="panel"><h2>Twoje odmiany <span className="badge">8</span></h2><div className="varieties">{varietyStats.map((v,i)=><div className="variety" key={v.name}><span className={'fruit '+(!i?'sour':'')}>{v.name.slice(0,1)}</span><div><strong>{v.name}</strong><p>{i?'Czereśnia':'Wiśnia'}</p></div><span className="muted">{fmt(v.kg)} kg</span></div>)}</div></section>
 </TabsContent>
 <TabsContent value="statistics"><OrchardStatistics records={records} plots={plots} year={year} years={years}/></TabsContent>
 <TabsContent value="harvest">
 <Tabs value={fruit} onValueChange={v=>{setFruit(v);setFilter('all')}}><TabsList className="fruit-switch"><TabsTrigger value="sour">Wiśnie</TabsTrigger><TabsTrigger value="sweet">Czereśnie</TabsTrigger></TabsList></Tabs>
 <div className="toolbar"><div>{fruit==='sweet'?<Choice label="Odmiana czereśni" value={filter} onChange={setFilter} options={[{value:'all',label:'Wszystkie czereśnie'},...varieties.filter(v=>v!=='Łutówka').map(v=>({value:v,label:v}))]}/>:<div><h2>Wszystkie wiśnie</h2><span className="muted">Łutówka · sezon {year}</span></div>}</div><button className="button" disabled={!device||auth} onClick={()=>start('harvest')}><Plus size={18}/>{fruit==='sour'?'Dodaj zbiór wiśni':'Dodaj zbiór czereśni'}</button></div>
 <div className="summary-grid"><div><span>Łącznie zebrano</span><strong>{fmt(visibleHarvests.reduce((s,r)=>s+weight(r),0))} kg</strong><span>{fmt(visibleHarvests.reduce((s,r)=>s+r.boxes5,0))} × 5 kg · {fmt(visibleHarvests.reduce((s,r)=>s+r.boxes10,0))} × 10 kg</span></div><div><span>Wartość sprzedaży</span><strong>{priced.length?fmt(priced.reduce((s,r)=>s+saleValue(r),0))+' zł':'—'}</strong><span>{priced.length} z {visibleHarvests.length} wpisów z ceną</span></div><div><span>Średnia cena sprzedaży</span><strong>{priced.length?fmt(priced.reduce((s,r)=>s+saleValue(r),0)/priced.reduce((s,r)=>s+weight(r),0))+' zł/kg':'—'}</strong><span>Ważona masą wpisów z ceną</span></div></div>
 <section className="panel">{visibleHarvests.length?<RecordList list={visibleHarvests}/>:<EmptyState title={fruit==='sour'?'Brak zbiorów wiśni w tym sezonie':'Brak zbiorów czereśni w tym sezonie'} description="Dodaj pierwszy wpis lub wybierz inny sezon."/>}</section></TabsContent>
 <TabsContent value="work">
 <Tabs value={workFilter} onValueChange={setWorkFilter}><TabsList className="work-switch"><TabsTrigger value="Oprysk">Opryski</TabsTrigger><TabsTrigger value="Nawożenie">Nawożenie</TabsTrigger><TabsTrigger value="Podlewanie">Podlewanie</TabsTrigger><TabsTrigger value="history">Obserwacje / historia</TabsTrigger></TabsList></Tabs>
 <div className="toolbar"><h2>{workFilter==='history'?'Obserwacje i wcześniejsze prace':workFilter==='Oprysk'?'Opryski':workFilter}</h2><button className="button" disabled={!device||auth} onClick={()=>start(workFilter==='history'?'observation':'treatment')}><Plus size={18}/>{workFilter==='Oprysk'?'Dodaj oprysk':workFilter==='Nawożenie'?'Dodaj nawożenie':workFilter==='Podlewanie'?'Dodaj podlewanie':'Dodaj obserwację'}</button></div>
 <PlanList records={records} plots={plots} disabled={!device||auth||syncing} pending={pendingIds} onAdd={start} onDelete={setRemove} onSave={save}/><div className="summary-grid"><div><span>Wpisy w tej kategorii</span><strong>{visibleWorks.length}</strong></div>{workFilter==='Podlewanie'&&<div><span>Zapisana woda</span><strong>{fmt(water)} m³</strong></div>}<div><span>Koszt tej kategorii</span><strong>{fmt(visibleWorks.reduce((s,r)=>s+(r.kind==='treatment'?r.cost:0),0))} zł</strong></div></div><section className="panel">{visibleWorks.length?<RecordList list={visibleWorks}/>:<EmptyState title="Brak wpisów w tej kategorii" description="Wpisy pojawią się tutaj po zapisaniu."/>}</section></TabsContent>
 <TabsContent value="warehouse"><Warehouse records={records} year={year} disabled={!device||auth||syncing} pending={pendingIds} onAdd={start} onDelete={setRemove}/></TabsContent>
 <TabsContent value="plots"><div className="toolbar"><p className="muted">Dodaj dwa sady wiśniowe jako osobne kwatery, a sad czereśniowy jako jedną kwaterę z wieloma odmianami.</p><button className="button" disabled={!device||auth} onClick={()=>start('plot')}><Plus size={18}/>Dodaj kwaterę</button></div>{plots.length?<div className="plot-grid">{plots.map(p=><section className="panel" key={p.id}><div className="toolbar"><div><h2>{p.name}</h2><span className="muted">{plotFruit(p)==='sour'?'Wiśnie':'Czereśnie'} · {plotVarieties(p).join(', ')} · {p.area?`${fmt(p.area)} ha`:'powierzchnia niepodana'}{p.plantedYear&&` · sadzenie ${p.plantedYear}`}</span></div><button className="icon-btn" aria-label={`Edytuj kwaterę ${p.name}`} disabled={pendingIds.has(p.id)} onClick={()=>start('plot',p)}><Pencil/></button></div><div className="plot-numbers"><div><strong>{fmt(treesFor(p,records))}</strong><span>drzew obecnie</span></div><div><strong>{fmt(harvests.filter(r=>r.plotId===p.id).reduce((s,r)=>s+weight(r),0))}</strong><span>kg w sezonie {year}</span></div></div>{p.area>0&&<p className="muted">{fmt(harvests.filter(r=>r.plotId===p.id).reduce((s,r)=>s+weight(r),0)/p.area/1000)} t/ha · masa z wpisów</p>}{p.rootstock&&<p className="muted">Podkładka: {p.rootstock}</p>}<div className="toolbar"><button className="button secondary" onClick={()=>start('trees',{id:'',kind:'trees',plotId:p.id,treeChange:-1,date:today(),note:'',version:0})}>Ubytek / dosadzenie</button><button className="icon-btn" disabled={pendingIds.has(p.id)} aria-label={`Usuń kwaterę ${p.name}`} onClick={()=>setRemove(p)}><Trash2/></button></div></section>)}</div>:<section className="panel"><EmptyState title="Dodaj pierwszą kwaterę" description="Podaj nazwę, gatunek, odmiany i początkową liczbę drzew całej kwatery. Potem zapisuj ubytki i dosadzenia." action={device&&!auth?'Dodaj kwaterę':undefined} onClick={()=>start('plot')}/></section>}<section className="panel"><h2>Zmiany liczby drzew · {year}</h2>{changes.length?<RecordList list={changes}/>:<p className="muted">Brak zapisanych ubytków i dosadzeń w tym sezonie.</p>}</section></TabsContent>
 </Tabs><section className="export-row"><span className="muted">Twoje dane, zawsze pod ręką.</span><div className="button-group"><button className="button secondary" disabled={!device} onClick={exportCSV}><Download size={17}/>Eksport sezonu CSV</button><button className="link-btn" disabled={!device} onClick={()=>download(`moj-sad-kopia-${today()}.json`,JSON.stringify({format:'moj-sad-v1',exportedAt:new Date().toISOString(),...device},null,2),'application/json')}>Pełna kopia danych</button></div></section>
 </main><footer>Mój Sad · Wiśnie i czereśnie · {year}</footer>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal(null)}}><DialogContent className="dialog-box"><DialogTitle>{modal?.record?.id?'Edytuj wpis':modal?`Dodaj: ${titles[modal.kind].toLowerCase()}`:''}</DialogTitle><DialogDescription>{modal?.kind==='harvest'?'Zapisz ilość owoców i opcjonalną cenę sprzedaży.':'Uzupełnij dane dotyczące Twojego gospodarstwa.'}</DialogDescription>{modal&&(modal.kind==='stock'||modal.kind==='purchase')?<InventoryForm kind={modal.kind} record={modal.record} records={records} onSave={save} busy={busy} setBusy={setBusy} error={formError} setError={setFormError}/>:modal?.kind==='plan'?<PlanForm record={modal.record} plots={plots} onSave={save} busy={busy} setBusy={setBusy} error={formError} setError={setFormError}/>:modal&&<EntryForm key={modal.kind+(modal.record?.id||'new')} kind={modal.kind} record={modal.record} defaultVariety={modal.defaultVariety} defaultTreatment={modal.defaultTreatment} plots={plots} records={records} onSave={save} busy={busy} setBusy={setBusy} error={formError} setError={setFormError}/>}</DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogTitle>Usunąć ten wpis?</AlertDialogTitle><AlertDialogDescription>{remove?.kind==='plot'?'Kwaterę można usunąć tylko wtedy, gdy nie ma powiązanych zbiorów, zabiegów i zmian drzew.':'Wpis zostanie usunięty z rejestru i zestawień. Możesz wcześniej pobrać kopię danych.'}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Anuluj</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void deleteRecord()}}>Usuń wpis</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}

function EntryForm({kind,record,defaultVariety='Łutówka',defaultTreatment='Oprysk',plots,records,onSave,busy,setBusy,error,setError}:{kind:Kind,record?:OrchardRecord,defaultVariety?:string,defaultTreatment?:string,plots:Plot[],records:OrchardRecord[],onSave:(r:OrchardRecord)=>Promise<void>,busy:boolean,setBusy:(b:boolean)=>void,error:string,setError:(s:string)=>void}){
 const r=record as any;
 const stocks=records.filter((s):s is Stock=>s.kind==='stock');
 const [materials,setMaterials]=useState<{stockId:string,amount:number,unit:'kg'|'l'}[]>(r?.materials??[]),[stage,setStage]=useState(r?.stage||'');
 const [date,setDate]=useState(r?.date||today()),[plotId,setPlotId]=useState(r?.plotId||'none'),[variety,setVariety]=useState(r?.variety||defaultVariety);
 const [fruitType,setFruitType]=useState(r?.fruit??(plots.find(p=>p.id===r?.plotId)?plotFruit(plots.find(p=>p.id===r.plotId)!):(r?.variety||defaultVariety)==='Łutówka'?'sour':'sweet'));
 const [selectedVarieties,setSelectedVarieties]=useState<string[]>(r?.kind==='plot'?plotVarieties(r):[defaultVariety]);
 const [weightMode,setWeightMode]=useState(r?.weightKg!=null?'kg':r?.id?'boxes':defaultVariety==='Łutówka'?'kg':'boxes');
 const [kilograms,setKilograms]=useState(String(r?.weightKg??'')),[price,setPrice]=useState(r?.pricePerKg!=null?String(r.pricePerKg):'');
 const effectiveMode=fruitType==='sour'?weightMode:'boxes';
 const [boxes5,setBoxes5]=useState(String(r?.boxes5??0)),[boxes10,setBoxes10]=useState(String(r?.boxes10??0));
 const entryKg=effectiveMode==='kg'?Number(kilograms):Number(boxes5)*5+Number(boxes10)*10;
 const [treatment,setTreatment]=useState(r?.treatment||defaultTreatment),[unit,setUnit]=useState(r?.unit||(defaultTreatment==='Podlewanie'?'m³':'kg')),[direction,setDirection]=useState(r?.treeChange>0?'add':'remove');
 const id=useRef(record?.id||crypto.randomUUID());
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);const s=(key:string)=>String(f.get(key)||'');const n=(key:string)=>Number(s(key).replace(',','.'));const base={id:id.current,kind,date,note:s('note'),version:record?.version??0};let next:any;
  if(kind==='plot')next={...base,name:s('name'),variety:fruitType==='sour'?'Łutówka':selectedVarieties[0],varieties:fruitType==='sour'?['Łutówka']:selectedVarieties,area:n('area'),initialTrees:n('initialTrees'),plantedYear:s('plantedYear')?n('plantedYear'):null,rootstock:s('rootstock')};
  if(kind==='harvest')next={...base,plotId:plotId==='none'?null:plotId,variety,boxes5:effectiveMode==='kg'?0:Number(boxes5),boxes10:effectiveMode==='kg'?0:Number(boxes10),weightKg:effectiveMode==='kg'?Number(kilograms):null,pricePerKg:price.trim()===''?null:Number(price)};
  if(kind==='treatment')next={...base,plotId:plotId==='none'?null:plotId,treatment,product:s('product'),amount:n('amount'),unit,cost:n('cost'),materials:['Oprysk','Nawożenie'].includes(treatment)?materials:[],fruit:treatment==='Oprysk'?fruitType:null,stage:treatment==='Oprysk'?stage||null:null};
  if(kind==='trees')next={...base,plotId,treeChange:n('treeCount')*(direction==='add'?1:-1)};
  if(kind==='observation')next={...base,plotId:plotId==='none'?null:plotId,name:s('name')};
  try{await onSave(next)}catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 return <form className="fields" onSubmit={submit}><div><label htmlFor="entry-date">{kind==='plot'?'Data stanu początkowego':'Data'}</label><input id="entry-date" type="date" required value={date} onChange={e=>setDate(e.target.value)}/></div>
 {kind==='plot'&&<Tabs value={fruitType} onValueChange={v=>{setFruitType(v);setSelectedVarieties(v==='sour'?['Łutówka']:varieties.filter(x=>x!=='Łutówka'))}}><TabsList className="fruit-switch"><TabsTrigger value="sour">Wiśnie</TabsTrigger><TabsTrigger value="sweet">Czereśnie</TabsTrigger></TabsList></Tabs>}
 {kind==='harvest'&&<Tabs value={fruitType} onValueChange={v=>{setFruitType(v);setVariety(v==='sour'?'Łutówka':'Wanda');setPlotId('none');setWeightMode(v==='sour'?'kg':'boxes')}}><TabsList className="fruit-switch"><TabsTrigger value="sour">Wiśnie</TabsTrigger><TabsTrigger value="sweet">Czereśnie</TabsTrigger></TabsList></Tabs>}
 {kind==='treatment'&&treatment==='Oprysk'&&<Choice label="Gatunek" value={fruitType} onChange={v=>{setFruitType(v as 'sour'|'sweet');setPlotId('none')}} options={[{value:'sour',label:'Wiśnie'},{value:'sweet',label:'Czereśnie'}]}/>}
 {kind!=='plot'&&<Choice label="Kwatera" value={plotId} onChange={v=>{setPlotId(v);const p=plots.find(p=>p.id===v);if(p&&kind==='treatment')setFruitType(plotFruit(p));if(p&&!plotVarieties(p).includes(variety))setVariety(plotVarieties(p)[0])}} options={[{value:'none',label:kind==='trees'?'Wybierz kwaterę':'Bez przypisania do kwatery'},...plots.filter(p=>(kind!=='harvest'&&!(kind==='treatment'&&treatment==='Oprysk'))||plotFruit(p)===fruitType).map(p=>({value:p.id,label:p.name+' · '+(plotFruit(p)==='sour'?'Wiśnie':'Czereśnie')}))]}/>}
 {kind==='harvest'&&fruitType==='sweet'&&<Choice label="Odmiana" value={variety} onChange={setVariety} options={(plots.find(p=>p.id===plotId)?plotVarieties(plots.find(p=>p.id===plotId)!):varieties.filter(v=>v!=='Łutówka')).map(v=>({value:v,label:v}))}/>}
 {kind==='plot'&&fruitType==='sweet'&&<fieldset className="variety-picker"><legend>Odmiany w tej kwaterze</legend>{varieties.filter(v=>v!=='Łutówka').map(v=><label key={v}><input type="checkbox" checked={selectedVarieties.includes(v)} onChange={e=>setSelectedVarieties(current=>e.target.checked?[...current,v]:current.filter(x=>x!==v))}/>{v}</label>)}<p className="progress-note">Wybierz co najmniej jedną odmianę. Wszystkie należą do tej samej kwatery.</p></fieldset>}
 {kind==='plot'&&fruitType==='sour'&&<p className="progress-note">Wiśnie · Łutówka</p>}
 {kind==='harvest'&&fruitType==='sour'&&<p className="progress-note">Wiśnie · Łutówka</p>}
 {kind==='harvest'&&<>
 {fruitType==='sour'&&<Choice label="Sposób wpisania ilości" value={weightMode} onChange={setWeightMode} options={[{value:'kg',label:'Kilogramy'},{value:'boxes',label:'Skrzynki 5 i 10 kg'}]}/>}
 {effectiveMode==='kg'?<div><label htmlFor="kilograms">Liczba kilogramów</label><input id="kilograms" type="number" inputMode="decimal" min="0.01" max="100000000" step="0.01" required value={kilograms} onChange={e=>setKilograms(e.target.value)}/></div>:<div className="form-row"><div><label htmlFor="boxes5">Skrzynki 5 kg</label><input id="boxes5" type="number" inputMode="numeric" min="0" max="1000000" step="1" required value={boxes5} onChange={e=>setBoxes5(e.target.value)}/></div><div><label htmlFor="boxes10">Skrzynki 10 kg</label><input id="boxes10" type="number" inputMode="numeric" min="0" max="1000000" step="1" required value={boxes10} onChange={e=>setBoxes10(e.target.value)}/></div></div>}
 <div className="total"><span>{effectiveMode==='kg'?'Masa zbioru':'Masa ze skrzynek'}</span><strong>{fmt(entryKg)} kg</strong></div>
 <div><label htmlFor="price">Cena sprzedaży (zł/kg)</label><input id="price" type="number" inputMode="decimal" min="0" max="100000000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Opcjonalnie — uzupełnij po sprzedaży"/></div>
 {price.trim()!==''&&<div className="total"><span>Wartość sprzedaży</span><strong>{fmt(Math.round((entryKg*Number(price)+Number.EPSILON)*100)/100)} zł</strong></div>}
 <p className="progress-note">Cena dotyczy całej ilości w tym wpisie. Jeśli sprzedajesz partie w różnych cenach, zapisz je osobno.</p>
 </>}
 {kind==='plot'&&<><div><label htmlFor="name">Nazwa sadu / kwatery</label><input id="name" name="name" required maxLength={100} placeholder="np. Sad czereśniowy lub Wiśnie za domem" defaultValue={r?.name}/></div><div className="form-row"><div><label htmlFor="initialTrees">Początkowa liczba drzew w całej kwaterze</label><input id="initialTrees" name="initialTrees" type="number" min="0" max="1000000" step="1" inputMode="numeric" required defaultValue={r?.initialTrees??''}/></div><div><label htmlFor="area">Powierzchnia (ha)</label><input id="area" name="area" type="number" min="0" max="100000" step="0.0001" inputMode="decimal" defaultValue={r?.area||''} placeholder="Opcjonalnie"/></div></div><div className="form-row"><div><label htmlFor="plantedYear">Rok sadzenia</label><input id="plantedYear" name="plantedYear" type="number" min="1900" max="2200" step="1" defaultValue={r?.plantedYear||''} placeholder="Opcjonalnie"/></div><div><label htmlFor="rootstock">Podkładka</label><input id="rootstock" name="rootstock" maxLength={100} defaultValue={r?.rootstock} placeholder="Opcjonalnie"/></div></div><p className="progress-note">Późniejsze ubytki i dosadzenia zapisuj jako zmiany liczby drzew.</p></>}
 {kind==='treatment'&&<><Choice label="Rodzaj zabiegu" value={treatment} onChange={v=>{setTreatment(v);if(v==='Podlewanie')setUnit('m³')}} options={[...activeTreatments,...(r?.treatment&&!activeTreatments.includes(r.treatment)?[r.treatment]:[])].map(t=>({value:t,label:t}))}/>{treatment==='Oprysk'&&<GrowthStageField value={stage} onChange={setStage}/>}<div><label htmlFor="product">Nawóz, preparat lub opis pracy</label><input id="product" name="product" maxLength={200} defaultValue={r?.product} placeholder="np. nazwa nawozu"/></div>{['Oprysk','Nawożenie'].includes(treatment)&&<MaterialsField value={materials} onChange={setMaterials} stocks={stocks} records={records} editingId={record?.id}/>}<div className="form-row"><div><label htmlFor="amount">Ilość cieczy / inne dane zabiegu</label><input id="amount" name="amount" type="number" min="0" max="100000000" step="0.01" inputMode="decimal" defaultValue={r?.amount??0}/></div><Choice label="Jednostka" value={unit} onChange={setUnit} options={['kg','l','g','ml','m³','godz.'].map(v=>({value:v,label:v}))}/></div><div><label htmlFor="cost">Koszt (zł)</label><input id="cost" name="cost" type="number" min="0" max="100000000" step="0.01" inputMode="decimal" defaultValue={r?.cost??0}/></div><p className="progress-note">Zużycie środków wpisz w sekcji magazynu. W tym polu możesz podać np. ilość wody, a dawkę na hektar w uwagach.</p></>}
 {kind==='trees'&&<><Choice label="Zmiana" value={direction} onChange={setDirection} options={[{value:'remove',label:'Ubytek / usunięcie drzew'},{value:'add',label:'Dosadzenie drzew'}]}/><div><label htmlFor="treeCount">Liczba drzew</label><input id="treeCount" name="treeCount" type="number" required min="1" max="1000000" step="1" inputMode="numeric" defaultValue={Math.abs(r?.treeChange||1)}/></div></>}
 {kind==='observation'&&<div><label htmlFor="name">Co zaobserwowano?</label><input id="name" name="name" required maxLength={160} defaultValue={r?.name} placeholder="np. uszkodzenia po przymrozku"/></div>}
 <div><label htmlFor="note">{kind==='trees'?'Przyczyna / uwagi':'Uwagi'}</label><textarea id="note" name="note" maxLength={2000} defaultValue={r?.note} placeholder="Opcjonalnie"/></div>{error&&<p className="notice error" role="alert">{error}</p>}<button className="button" type="submit" disabled={busy||(kind==='trees'&&plotId==='none')||(kind==='plot'&&fruitType==='sweet'&&!selectedVarieties.length)}>{busy?'Zapisywanie…':'Zapisz wpis'}</button></form>
}
