'use client';
import {useRef,useState,type FormEvent} from 'react';
import {Plus,Pencil,Trash2,CalendarDays} from 'lucide-react';
import {today,plotFruit,reminderStarts,duePlans,type OrchardRecord,type Plot,type Plan,type Kind} from '@/lib/orchard';
import {growthStages,flowerBudStages,growthStageSource,stageLabel} from '@/lib/growth-stages';
import {downloadText} from './orchard-inventory';
export function GrowthStageField({value,onChange}:{value:string,onChange:(s:string)=>void}){
 const isBud=flowerBudStages.some(s=>s.value===value),known=isBud||growthStages.some(s=>s.value===value),[custom,setCustom]=useState(!!value&&!known);
 return <div><label htmlFor="growth-stage">Faza rozwoju</label><select id="growth-stage" value={custom?'other':isBud?'inflorescence':value||'none'} onChange={e=>{setCustom(e.target.value==='other');onChange(e.target.value==='none'||e.target.value==='other'?'':e.target.value)}}><option value="none">Nie podano</option>{growthStages.map(s=><option key={s.value} value={s.value}>{s.label}{s.bbch?' · BBCH '+s.bbch:''}</option>)}<option value="other">Inna faza — własny opis</option></select>{(value==='inflorescence'||isBud)&&<><label htmlFor="bud-detail">Etap pąka (opcjonalnie)</label><select id="bud-detail" value={isBud?value:'inflorescence'} onChange={e=>onChange(e.target.value)}><option value="inflorescence">Ogólnie — rozwój kwiatostanów</option>{flowerBudStages.map(s=><option key={s.value} value={s.value}>{s.label} · BBCH {s.bbch}</option>)}</select></>}{custom&&<><label htmlFor="custom-stage">Własna nazwa fazy</label><input id="custom-stage" maxLength={160} value={value} required onChange={e=>onChange(e.target.value)}/></>}<p className="progress-note"><a href={growthStageSource+'#page=4'} target="_blank" rel="noreferrer" className="link-btn">8 głównych faz BBCH — Instytut Ogrodnictwa</a>. „Po zbiorach” to dodatkowy etap do wpisów i planowania.</p></div>;
}
function calendar(plan:Plan){
 const escape=(s:string)=>s.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(';','\\;').replaceAll(',','\\,');
 const date=plan.date.replaceAll('-',''),end=new Date(Date.parse(plan.date+'T12:00:00Z')+86400000).toISOString().slice(0,10).replaceAll('-','');
 const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Moj Sad//PL','BEGIN:VEVENT',`UID:${plan.id}@moj-sad`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${date}`,`DTEND;VALUE=DATE:${end}`,`SUMMARY:${escape(plan.name)}`,`DESCRIPTION:${escape((plan.fruit==='sour'?'Wiśnie':'Czereśnie')+' — '+stageLabel(plan.stage)+'\n'+plan.note)}`,'BEGIN:VALARM',`TRIGGER:-P${plan.leadDays}D`,'ACTION:DISPLAY',`DESCRIPTION:${escape(plan.name)}`,'END:VALARM','END:VEVENT','END:VCALENDAR'];
 downloadText(`moj-sad-przypomnienie-${plan.date}.ics`,lines.join('\r\n')+'\r\n','text/calendar;charset=utf-8');
}
export function PlanList({records,plots,disabled,pending,onAdd,onDelete,onSave,compact=false}:{records:OrchardRecord[],plots:Plot[],disabled:boolean,pending:Set<string>,onAdd:(kind:Kind,r?:OrchardRecord)=>void,onDelete:(r:OrchardRecord)=>void,onSave:(r:OrchardRecord)=>Promise<void>,compact?:boolean}){
 const [error,setError]=useState('');
 const plans=compact?duePlans(records):records.filter((r):r is Plan=>r.kind==='plan').sort((a,b)=>Number(a.completed)-Number(b.completed)||a.date.localeCompare(b.date));
 if(compact&&!plans.length)return null;
 return <section className="panel"><div className="toolbar"><h2>{compact?'Przypomnienia':'Planowane opryski i przypomnienia'}</h2>{!compact&&<button className="button" disabled={disabled} onClick={()=>onAdd('plan')}><Plus size={18}/>Dodaj przypomnienie</button>}</div>{error&&<p className="notice error" role="alert">{error}</p>}{plans.map(p=><div className="record" key={p.id}><div><strong>{p.name}</strong>{p.completed&&<span className="badge">Zakończone</span>}<p>{p.date} · {p.fruit==='sour'?'Wiśnie':'Czereśnie'} · {plots.find(q=>q.id===p.plotId)?.name||'Bez kwatery'}</p><p>{stageLabel(p.stage)} · przypomnienie od {reminderStarts(p)}</p>{!p.completed&&p.date<today()&&<p className="stock-alert">Termin minął</p>}{p.note&&<p className="note-text">{p.note}</p>}<div className="button-group"><button className="link-btn" disabled={disabled||pending.has(p.id)} onClick={async()=>{setError('');try{await onSave({...p,completed:!p.completed})}catch(e){setError((e as Error).message)}}}>{p.completed?'Przywróć przypomnienie':'Oznacz jako zakończone'}</button><button className="link-btn" onClick={()=>calendar(p)}><CalendarDays size={15} className="inline-icon"/>Do kalendarza telefonu</button></div></div><div className="record-actions"><button className="icon-btn" aria-label={`Edytuj przypomnienie ${p.name}`} disabled={disabled||pending.has(p.id)} onClick={()=>onAdd('plan',p)}><Pencil/></button><button className="icon-btn" aria-label={`Usuń przypomnienie ${p.name}`} disabled={disabled||pending.has(p.id)} onClick={()=>onDelete(p)}><Trash2/></button></div></div>)}{!plans.length&&<p className="muted">Ustaw własny termin, np. sprawdzenie kwitnienia lub planowany oprysk.</p>}{!compact&&<p className="progress-note">Przypomnienie pojawia się w Przeglądzie po otwarciu aplikacji. Aby otrzymać alarm poza aplikacją, pobierz wpis i dodaj go do kalendarza telefonu. Termin ustawiasz według obserwacji sadu; plan nie zmniejsza stanu magazynu. Wykonany zabieg zapisuj osobno.</p>}</section>;
}
export function PlanForm({record,plots,onSave,busy,setBusy,error,setError}:{record?:OrchardRecord,plots:Plot[],onSave:(r:OrchardRecord)=>Promise<void>,busy:boolean,setBusy:(b:boolean)=>void,error:string,setError:(s:string)=>void}){
 const r=record?.kind==='plan'?record:undefined,id=useRef(r?.id||crypto.randomUUID());
 const [fruit,setFruit]=useState(r?.fruit||'sour'),[plotId,setPlotId]=useState(r?.plotId||'none'),[stage,setStage]=useState(r?.stage||'');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget),s=(k:string)=>String(f.get(k)||'');try{await onSave({id:id.current,kind:'plan',version:r?.version??0,date:s('date'),name:s('name'),note:s('note'),fruit,plotId:plotId==='none'?null:plotId,stage:stage||null,leadDays:Number(s('leadDays')),completed:r?.completed??false})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form className="fields" onSubmit={submit}><div><label htmlFor="plan-name">O czym przypomnieć?</label><input id="plan-name" name="name" required maxLength={160} defaultValue={r?.name} placeholder="np. Sprawdź kwitnienie i zaplanowany oprysk"/></div><div><label htmlFor="plan-fruit">Gatunek</label><select id="plan-fruit" value={fruit} onChange={e=>{setFruit(e.target.value as 'sour'|'sweet');setPlotId('none')}}><option value="sour">Wiśnie</option><option value="sweet">Czereśnie</option></select></div><div><label htmlFor="plan-plot">Kwatera</label><select id="plan-plot" value={plotId} onChange={e=>setPlotId(e.target.value)}><option value="none">Bez przypisania do kwatery</option>{plots.filter(p=>plotFruit(p)===fruit).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><GrowthStageField value={stage} onChange={setStage}/><div className="form-row"><div><label htmlFor="plan-date">Planowany termin</label><input id="plan-date" name="date" type="date" required defaultValue={r?.date||today()}/></div><div><label htmlFor="plan-lead">Przypomnij ile dni wcześniej?</label><input id="plan-lead" name="leadDays" type="number" required min="0" max="30" step="1" defaultValue={r?.leadDays??7}/></div></div><div><label htmlFor="plan-note">Środek / opis / uwagi</label><textarea id="plan-note" name="note" maxLength={2000} defaultValue={r?.note}/></div>{error&&<p className="notice error" role="alert">{error}</p>}<button className="button" type="submit" disabled={busy}>{busy?'Zapisywanie…':'Zapisz przypomnienie'}</button></form>;
}
