const escape = (text: string) => text.replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function loginPage(email: string, error = '', status = 200): Response {
  return new Response(`<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Zaloguj się — Mój Sad</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6f2;color:#203c2e;font-family:system-ui,-apple-system,sans-serif;min-height:100dvh;display:grid;place-items:center;padding:24px}.card{width:100%;max-width:420px;background:white;border:1px solid #dce5de;border-radius:20px;padding:32px;box-shadow:0 16px 60px #1739230c}.brand{font-size:18px;font-weight:700;color:#176145}h1{font-size:28px;margin:24px 0 8px}p{color:#65786e;line-height:1.6;font-size:14px}form{display:grid;gap:18px;margin-top:24px}label{display:block;font-size:14px;font-weight:600;margin-bottom:8px}input[type=email],input[type=password]{display:block;width:100%;min-height:48px;padding:12px;border:1px solid #cbd8ce;border-radius:9px;font:inherit;font-size:16px;color:#203c2e}input:focus-visible,button:focus-visible{outline:3px solid #a2c9b5;outline-offset:2px}.remember{display:flex;align-items:center;gap:10px;font-weight:400;margin:0;min-height:44px}.remember input{width:20px;height:20px;accent-color:#176145}button{background:#176145;color:white;border:0;border-radius:9px;padding:14px;font:inherit;font-weight:600;cursor:pointer;min-height:48px}.error{border-radius:9px;background:#fff0ef;color:#a52e36;padding:12px;margin:16px 0 0}small{display:block;color:#65786e;font-size:12px;margin-top:8px}@media(max-width:430px){.card{padding:24px}body{padding:16px}}
</style></head><body><main class="card"><div class="brand">🌱 Mój Sad</div><h1>Zaloguj się do sadu</h1><p>Twoje zbiory, zabiegi i magazyn w jednym miejscu.</p>${error?`<p class="error" role="alert">${escape(error)}</p>`:''}<form method="post" action="/api/auth/login"><div><label for="email">Login — e-mail</label><input id="email" name="email" type="email" autocomplete="username" required maxlength="254" value="${escape(email)}"></div><div><label for="password">Hasło</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024"></div><div><label class="remember"><input name="remember" type="checkbox" value="yes">Zapamiętaj to urządzenie</label><small>Nie będziesz musiał logować się ponownie przez 30 dni.</small></div><button type="submit">Zaloguj się</button></form></main></body></html>`, {status,headers:{
    'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow',
    'Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",
    'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin',
  }});
}
